### ISSUE TITLE
ida-7.1 crashing when loading ipyida plugin

### ISSUE THREAD

**Issue by RobinDavid** [eset/ipyida#13]
After updating from ida-7.0sp1 to ida-7.1, IPyIDA makes IDA to crash.

IDA segfault both when `ipyida.ida_plugin.load()` is launched from `idapythonrc.py` and manually in the python shell. Note that it seems to work when copy-pasting ida_plugin.py in the plugins directory of IDA.

I think it might have something to do with the *Qt5* version used but I am not sure.

Does it also occurs for you ?
_(I am using Debian testing)_

**Comment by aundro** [comment]
This is a bug in IDAPython 7.1 (because of the notion of NAMESPACE_AWARE that was introduced ( http://www.hexblog.com/?p=1151 ))

Please contact us on < support _at_ hex-rays.com > (mentioning your license ID) for fixed IDAPython components.

**Comment by RobinDavid** [comment]
I got it working by putting `ida_plugin.py` in the directory `ida-7.1/plugins` but thanks for your solution :wink:

**Comment by marc-etienne** [comment]
Thanks @aundro for the documenting the cause here, it saved me quite some time debugging this. Am I right to understand that `load_plugin` no longer accept absolute paths?

**Comment by marc-etienne** [comment]
Ok so it's an upstream bug with IDAPython. I sent an email sent to support for updated binary.

Since I can't redistribute it, I'll try to find a workaround (or at least display a warning) for IPyIDA users that updated to 7.1 so it doesn't crash until the next IDA release.

**Comment by marc-etienne** [comment]
I agree, I will update the installer when I have a minute to look into it.

**Comment by marc-etienne** [comment]
Adding the stub in `$IDADIR/plugins/` is much nicer and as less side effects. I changed in install script to do that instead. If anyone wants to test, here is how you can install from the `master` branch:

```python
IPYIDA_PACKAGE_LOCATION="https://github.com/eset/ipyida/archive/master.tar.gz"
import urllib2
exec urllib2.urlopen('https://github.com/eset/ipyida/raw/master/install_from_ida.py').read()
```
