### ISSUE TITLE
pip.main is not supported since pip 10.0.0

### ISSUE THREAD

**Issue by trietptm** [eset/ipyida#14]
Hi, since pip 10.0.0, we will get the installation error: 
`AttributeError: 'module' object has no attribute 'main'`
because pip.main is not supported.

**Comment by marc-etienne** [comment]
This is fixed in the master branch. I'm launching pip in child process instead. Can you test it? Here is how you can install from the `master` branch:

```
IPYIDA_PACKAGE_LOCATION="https://github.com/eset/ipyida/archive/master.tar.gz"
import urllib2
exec urllib2.urlopen('https://github.com/eset/ipyida/raw/master/install_from_ida.py').read()
```

**Comment by trietptm** [comment]
Hi, this is fixed, thank you 👍 .

**Comment by trietptm** [comment]
I've just have an exception from IPythonKernel:
Failed while executing plugin_t.run():
Traceback (most recent call last):
  File "C:\python27-x64\lib\site-packages\ipyida\ida_plugin.py", line 27, in run
    self.kernel.start()
  File "C:\python27-x64\lib\site-packages\ipyida\kernel.py", line 93, in start
    "IDA's prompt.".format("IPythonKernel.start"))
Exception: IPythonKernel.start must be called from idapythonrc.py or IDA's prompt.

![snap 2018-07-07 at 22 53 50](https://user-images.githubusercontent.com/526959/42412561-d3a03c1e-8238-11e8-84c3-a0d6da89bf61.png)

**Comment by marc-etienne** [comment]
I can't seem to reproduce. What version of IDA is this? How is IPyIDA installed?

**Comment by trietptm** [comment]
I ran these commands on the Python console of IDA 7.0 about 3 times:
```
IPYIDA_PACKAGE_LOCATION="https://github.com/eset/ipyida/archive/master.tar.gz"
import urllib2
exec urllib2.urlopen('https://github.com/eset/ipyida/raw/master/install_from_ida.py').read()
```

**Comment by marc-etienne** [comment]
Try it again, it should be fixed.

**Comment by trietptm** [comment]
It's fixed now, thanks.

**Comment by trietptm** [comment]
Hi, I see the tab auto-completion while using IPython Console doesn't work anymore but tab-auto-completion still works in the Output window.
