### ISSUE TITLE
How do we uninstall ipyida?

### ISSUE THREAD

**Issue by abhcs** [eset/ipyida#16]
Is there an uninstall script? If not, which files need to be manually removed?

**Comment by marc-etienne** [comment]
There is no script as of now. You could uninstall the package with `python -mpip uninstall ipyida` and remove the `ipyida.py` (and `pyc` if it exists) in `$USER_IDA_DIR/plugins`:

```
import os, idaapi
ipyida_stub_path = os.path.join(idaapi.get_user_idadir(), "plugins", "ipyida.py")
os.remove(ipyida_stub_path)
os.remove(ipyida_stub_path + "c")
```
