### ISSUE TITLE
No such file or directory 'C:/Program Files (x86)/IDA 6.8/plugins/ipyida.py'

### ISSUE THREAD

**Issue by lawly** [eset/ipyida#17]
I'm using IDA Pro 6.8.150423. The python version shipped with IDA does not work because of the outdated SSL version so I use 2.7.9. I'm running ipython 5.8.0 and the most recent pip version. Everytime when running the command to install ipyida i get:

```
[+] ipyida.py added to user plugins
[Errno 2] No such file or directory: 'C:/Program Files (x86)/IDA 6.8/plugins/ipyida.py'
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.8\python\idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
IOError: [Errno 2] No such file or directory: 'C:/Program Files (x86)/IDA 6.8/plugins/ipyida.py'

[+] IPyIDA Installation successful. Use <Shift+.> to open the console.
```

What am I doing wrong?
Running as admin did not solve it either.
The directory does exist but the file does not. It's all installed in default directories.

**Comment by izhak2** [comment]
I managed to bypass this by following the install_from_ida.py script manually. 
To use the pip programatically, I had to import it internally:
`from pip._internal import main as pipmain` and used it instead, ex: `pipmain(['install', "--upgrade", "pip"])`
Then I copied ipyida.py and ipyida_plugin_stub.py from the user's roaming plugins folder (AppData\Roaming\Hex-Rays\IDA Pro\plugins) to the plugins folder of IDA (inside Program Files). Afterwards, launching idaapi.load_plugin('ipyida.py') from the Python console and clicking Shift + . popped the desired ipython console.
