### ISSUE TITLE
Not responding to ConnectionFileMixin.connection_file

### ISSUE THREAD

**Issue by esemwy** [eset/ipyida#19]
At some point I had ipyida working within a jupyter notebook  using a configuration file hack and ```remote_ikernel```. At some point, an upgrade broke the functionality and I can't seem to get it working again. I can verify that the Jupyter creates the connection file properly, but ipyida doesn't seem to pick up the configuration. Any suggestions would be welcome.

**jupyter_notebook_config.py**
```
c.ConnectionFileMixin.connection_file = os.environ.get('IPY_CONNECTION_FILE', "kernel-{}.json".format(os.getppid()))
```
**rik_local_idapro32bit/kernel.json**
```
{
  "argv": [
    "/usr/bin/python", 
    "-m", 
    "remote_ikernel", 
    "--interface", 
    "local", 
    "--kernel_cmd", 
    "IPY_CONNECTION_FILE={connection_file} DISPLAY=:0 /opt/ida-7.1/ida", 
    "{connection_file}"
  ], 
  "display_name": "Local IDA Pro (32-bit)", 
  "remote_ikernel_argv": [
    "/usr/local/bin/remote_ikernel", 
    "manage", 
    "--add", 
    "--kernel_cmd=IPY_CONNECTION_FILE={connection_file} DISPLAY=:0 /opt/ida-7.1/ida", 
    "--name=IDA Pro (32-bit)", 
    "--interface=local"
  ]
}
```

**Comment by marc-etienne** [comment]
Interesting. I won't support Jupyter notebook just yet but I'll keep this open for the remote_ikernel trick.

**Comment by marc-etienne** [comment]
IPyIDA 2.0 now support Jupyter Notebook, so closing this.
