### ISSUE TITLE
Error in IDA 6.8 with python2.7.12 for Win8(64 bit)

### ISSUE THREAD

**Issue by ultimatekid1214** [eset/ipyida#24]
Python>import urllib2; exec urllib2.urlopen('https://github.com/eset/ipyida/raw/stable/install_from_ida.py').read()
[+] Using already installed pip (version 8.1.1)
Collecting ipyida
  Using cached https://files.pythonhosted.org/packages/91/8d/67ae354e7780fe9004bfac6dddc3cb530588506f41d5face04a420cf84ec/ipyida-1.3-py2-none-any.whl
Collecting qtconsole>=4.3 (from ipyida)
  Using cached https://files.pythonhosted.org/packages/c7/45/1a50288305797fbca7c2039f9baefff1a9df603322874743fbb8408d8ec2/qtconsole-4.4.4-py2.py3-none-any.whl
Collecting ipykernel>=4.6 (from ipyida)
  Using cached https://files.pythonhosted.org/packages/11/0b/95330660f8cc5d63428b9886c800ea8d68842fd866389cf579acca4915be/ipykernel-5.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: ipykernel requires Python version 3.4 or above.
    
    ----------------------------------------

[.] ipyida system-wide package installation failed, trying user install
Collecting ipyida
  Using cached https://files.pythonhosted.org/packages/91/8d/67ae354e7780fe9004bfac6dddc3cb530588506f41d5face04a420cf84ec/ipyida-1.3-py2-none-any.whl
Collecting qtconsole>=4.3 (from ipyida)
  Using cached https://files.pythonhosted.org/packages/c7/45/1a50288305797fbca7c2039f9baefff1a9df603322874743fbb8408d8ec2/qtconsole-4.4.4-py2.py3-none-any.whl
Collecting ipykernel>=4.6 (from ipyida)
  Using cached https://files.pythonhosted.org/packages/11/0b/95330660f8cc5d63428b9886c800ea8d68842fd866389cf579acca4915be/ipykernel-5.1.0.tar.gz
    Complete output from command python setup.py egg_info:
    ERROR: ipykernel requires Python version 3.4 or above.
    
    ----------------------------------------

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<string>", line 91, in <module>
Exception: ipyida package installation failed

**Comment by marc-etienne** [comment]
I see ipykernel dropped support for Python 2 in v5. I've fixed dependencies and will release v1.4 soon with this fix.

**Comment by ultimatekid1214** [comment]
Have you fixed this error ? I still encounter this error.

**Comment by marc-etienne** [comment]
Fix is in `master` but not released yet. You can install IPyIDA from `master` using

```python
IPYIDA_PACKAGE_LOCATION="https://github.com/eset/ipyida/archive/master.tar.gz"
import urllib2
exec urllib2.urlopen('https://github.com/eset/ipyida/raw/master/install_from_ida.py').read()
```

**Comment by ultimatekid1214** [comment]
After installing, I got error as following:

[+] ipyida.py added to user plugins
[Errno 2] No such file or directory: 'C:/Program Files (x86)/IDA 6.8/plugins/ipyida.py'
Traceback (most recent call last):
  File "C:\Program Files (x86)\IDA 6.8\python\idaapi.py", line 601, in IDAPython_ExecScript
    execfile(script, g)
IOError: [Errno 2] No such file or directory: 'C:/Program Files (x86)/IDA 6.8/plugins/ipyida.py'

**Comment by marc-etienne** [comment]
Did you try restarting IDA? Is IPyIDA listed in Edit -> Plugins when you have a pdb open?

**Comment by ultimatekid1214** [comment]
when I copy ipyida_plugin_stub.py to the user’s plugins directory., then it's okay.
Thanks

**Comment by marc-etienne** [comment]
Great! I'm not sure why it wasn't copied by the install script. Enjoy IPyIDA!
