### ISSUE TITLE
Not compatible with latest qtconsole

### ISSUE THREAD

**Issue by ChiChou** [eset/ipyida#31]
After installation, the plugin could not be loaded:

> │[WARN] Could not load IPyIDA plugin. ipyida Python package doesn't seem to be installed.

Commented out the try/catch block I can see the root cause is that `qtconsole` has removed `qtconsole.qt_loaders` submodule, which caused the ImportError.

Temporary workaround:
`pip install qtconsole==4.3`

**Comment by marc-etienne** [comment]
Thanks for report and providing a workaround. This `qt_loaders` monkey patching was doomed to fail one day... Today is the day.

**Comment by ChiChou** [comment]
🎉
