### ISSUE TITLE
ida 7.4 python 3.8.5 - crash upon startup

### ISSUE THREAD

**Issue by galosss** [eset/ipyida#36]
after installing ipyida, having the above versions of ida and python, ida encounters a problem upon startup, and crashes immediately.

**Comment by gaasedelen** [comment]
I think this issue should be closed. This is almost certainly the fact that IDA 7.4 + Python 3.8 does not have working python Qt bindings.

c.f: 

* https://github.com/gaasedelen/lighthouse/issues/84#issuecomment-622009267
* https://www.hex-rays.com/blog/ida-7-4-and-python-3-8/

The solution is to use Python 3.6/3.7, or upgrade to IDA 7.5+ which fully supports Python 3.8 and has properly compiled Qt bindings for newer versions of Python.

**Comment by marc-etienne** [comment]
Hey @galosss,

I think @gaasedelen is right: it may be a problem with IDA/IDAPython itself and not IPyIDA.

If you still have problems please share the exact error message(s) so we can help further.

Cheers,
M-E
