### ISSUE TITLE
The idapythonrc.py script fails to import idaapi, idc and idautils

### ISSUE THREAD

**Issue by ricnar456** [eset/ipyida#38]
My script idapythonrc.py is located in my C: \ Users \ xxxx \ AppData \ Roaming \ Hex-Rays \ IDA Pro folder.

I tried uncommenting, commenting out the lines, but the files don't import.

I added the dark mode code to the file and the console correctly boots to black (That means the file is located correctly and has loaded fine)

**import qtconsole.styles
import ipyida.ida_qtconsole
ipyida.ida_qtconsole.set_widget_options(dict(
    style_sheet = qtconsole.styles.default_dark_style_sheet,
    syntax_style = qtconsole.styles.default_dark_syntax_style
))**

But the part of the script to import idaapi, idc and idautils has no effect and does not import the necessary files.

from idaapi import *
from idc import *
from idautils import *

They can be imported manually only

**Comment by ricnar456** [comment]
I can import the files from the idapython startup folder

![image](https://user-images.githubusercontent.com/8556494/102869914-0eeab280-441b-11eb-9651-f25e5c713853.png)

**Comment by marc-etienne** [comment]
Globals available in IPyIDA console should be **`ipyidarc.py`** not `idapythonrc.py`.

**Comment by marc-etienne** [comment]
- `idapythonrc.py` is loaded by IDAPython.
- `ipyidarc.py` is loaded but IPyIDA (in the context of the console).

**Comment by marc-etienne** [comment]
I'm closing this since I haven't heard back. I'm guessing your issue is fixed? Please reopen if it's not the case. Cheers!
