### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by greg-workspace** [eset/ipyida#41]
The default qtconsole font size in IDA Pro is too small. How to enlarge the font size?

**Comment by nyx0** [comment]
Maybe this https://qtconsole.readthedocs.io/en/stable/config_options.html and this https://github.com/eset/ipyida#customizing-the-ipython-console could help.

**Comment by marc-etienne** [comment]
Indeed, @nyx0's suggestion works fine. The following in `ipyidarc.py` set the font size to 30:

```python
import ipyida.ida_qtconsole
ipyida.ida_qtconsole.set_widget_options(dict(font_size=30))
```

Please reopen the ticket if it doesn't fit your need.
