### ISSUE TITLE
Does the readme documentation no longer match the current repository？

### ISSUE THREAD

**Issue by omgkaka** [eset/ipyida#54]
**Does the readme documentation no longer match the current repository？**
    Because the install command in the documentation points to the **"https://github.com/eset/ipyida/raw/stable/install_from_ida.py"** file, which doesn't actually exist in the repository?

**Comment by omgkaka** [comment]
Problems with my network. . .

**Comment by omgkaka** [comment]
Because the problem of my network，
Finally, the installation was successful through the command line：
 "import urllib.request; exec(urllib.request.urlopen('https://github.com/eset/ipyida/raw/master/install_from_ida.py').read())".

**Comment by marc-etienne** [comment]
Great! Happy to know it worked for you :)
