### ISSUE TITLE
IDA freezes when trying "open_notebook"

### ISSUE THREAD

**Issue by lazydaemon** [eset/ipyida#58]
When trying to open a notebook with ``open_notebook``, IDA freezes for some reason. I installed ipyida via ``import urllib.request; exec(urllib.request.urlopen('https://github.com/eset/ipyida/raw/stable/install_from_ida.py').read())
`` and everything seemed to work fine. I tried with different Python versions via ``idapyswitch`` but no success.

OS: ``macOS Venture 13.1``
Python: ``/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/Python3``
IDA: IDA Pro Version 8.2.221216 macOS arm64

Any idea how to debug or what the problem could be?

**Comment by marc-etienne** [comment]
Maybe it hangs while trying to install required components. Try `%open_notebook --skip-dependency-checks`, it should at least show what failed to install.

**Comment by lazydaemon** [comment]
<img width="589" alt="Screenshot 2022-12-23 at 17 03 42" src="https://user-images.githubusercontent.com/3420941/209364701-004d09d2-129c-4100-b037-f06687f4f913.png">
Does not work :-(.

**Comment by ramikg** [comment]
I've found a potential infinite loop during notebook creation.
Could you please apply the fix in #59 and see if it makes any difference?

**Comment by lazydaemon** [comment]
> I've found a potential infinite loop during notebook creation. Could you please apply the fix in #59 and see if it replaces the freezing with an error?

Yep. At least I got an error now.

```
%open_notebook --skip-dependency-checks
-> Starting notebook
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 get_ipython().run_line_magic('open_notebook', '--skip-dependency-checks')

File ~/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py:2364, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2362     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2363 with self.builtin_trap:
-> 2364     result = fn(*args, **kwargs)
   2365 return result

File /opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ipyida-2.0-py3.9.egg/ipyida/notebook.py:142, in NotebookManager.open_notebook(self, line)
    140 if nb_server_info is None:
    141     self.nb_proc.terminate()
--> 142     raise Exception("Couldn't start Jupyter Notebook")
    143 else:
    144     self.nb_pipe_thread = threading.Thread(target=self._notebook_stdout_thread)

Exception: Couldn't start Jupyter Notebook
INFO:ipyida_kernel:Exception in execute request:
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[1], line 1
----> 1 get_ipython().run_line_magic('open_notebook', '--skip-dependency-checks')

File ~/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py:2364, in InteractiveShell.run_line_magic(self, magic_name, line, _stack_depth)
   2362     kwargs['local_ns'] = self.get_local_scope(stack_depth)
   2363 with self.builtin_trap:
-> 2364     result = fn(*args, **kwargs)
   2365 return result

File /opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ipyida-2.0-py3.9.egg/ipyida/notebook.py:142, in NotebookManager.open_notebook(self, line)
    140 if nb_server_info is None:
    141     self.nb_proc.terminate()
--> 142     raise Exception("Couldn't start Jupyter Notebook")
    143 else:
    144     self.nb_pipe_thread = threading.Thread(target=self._notebook_stdout_thread)

Exception: Couldn't start Jupyter Notebook
INFO:ipyida_kernel:Aborting queue
INFO:ipyida_kernel:Finishing abort
```

**Comment by ramikg** [comment]
In the file `notebook.py`, try adding the following lines right before the return statement of `_get_running_notebook_config`:
```
        print(idb_path)
        print([s['notebook_dir'] for s in list_running_servers()])
```

What does it print?

**Comment by marc-etienne** [comment]
I have pushed some changes in 4ddf215 which should help us debug this. Can you try with the updated `notebook.py`?

**Comment by lazydaemon** [comment]
```
-> Starting notebook
usage: jupyter.py [-h] [--version] [--config-dir] [--data-dir] [--runtime-dir]
                  [--paths] [--json] [--debug]
                  [subcommand]

Jupyter: Interactive Computing

positional arguments:
  subcommand     the subcommand to launch

optional arguments:
  -h, --help     show this help message and exit
  --version      show the versions of core jupyter packages and exit
  --config-dir   show Jupyter config dir
  --data-dir     show Jupyter data dir
  --runtime-dir  show Jupyter runtime dir
  --paths        show all Jupyter paths. Add --json for machine-readable
                 format.
  --json         output paths as machine-readable json
  --debug        output debug information about paths

Available subcommands:

Jupyter command `jupyter-notebook` not found.

INFO:ipyida_kernel:Exception in execute request:
[0;31m---------------------------------------------------------------------------[0m
[0;31mException[0m                                 Traceback (most recent call last)
Cell [0;32mIn[2], line 1[0m
[0;32m----> 1[0m [43mget_ipython[49m[43m([49m[43m)[49m[38;5;241;43m.[39;49m[43mrun_line_magic[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mopen_notebook[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43m'[39;49m[43m)[49m

File [0;32m~/Library/Python/3.9/lib/python/site-packages/IPython/core/interactiveshell.py:2364[0m, in [0;36mInteractiveShell.run_line_magic[0;34m(self, magic_name, line, _stack_depth)[0m
[1;32m   2362[0m     kwargs[[38;5;124m'[39m[38;5;124mlocal_ns[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mget_local_scope(stack_depth)
[1;32m   2363[0m [38;5;28;01mwith[39;00m [38;5;28mself[39m[38;5;241m.[39mbuiltin_trap:
[0;32m-> 2364[0m     result [38;5;241m=[39m [43mfn[49m[43m([49m[38;5;241;43m*[39;49m[43margs[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m   2365[0m [38;5;28;01mreturn[39;00m result

File [0;32m/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/ipyida-2.0-py3.9.egg/ipyida/notebook.py:145[0m, in [0;36mNotebookManager.open_notebook[0;34m(self, line)[0m
[1;32m    143[0m     [38;5;28mself[39m[38;5;241m.[39mnb_proc[38;5;241m.[39mterminate()
[1;32m    144[0m     [38;5;28mprint[39m([38;5;28mself[39m[38;5;241m.[39mnb_proc[38;5;241m.[39mstdout[38;5;241m.[39mread())
[0;32m--> 145[0m     [38;5;28;01mraise[39;00m [38;5;167;01mException[39;00m([38;5;124m"[39m[38;5;124mCouldn[39m[38;5;124m'[39m[38;5;124mt start Jupyter Notebook[39m[38;5;124m"[39m)
[1;32m    146[0m [38;5;28;01melse[39;00m:
[1;32m    147[0m     [38;5;28mself[39m[38;5;241m.[39mnb_pipe_thread [38;5;241m=[39m threading[38;5;241m.[39mThread(target[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39m_notebook_stdout_thread)

[0;31mException[0m: Couldn't start Jupyter Notebook
INFO:ipyida_kernel:Aborting queue
INFO:ipyida_kernel:Finishing abort
```

**Comment by marc-etienne** [comment]
Looks like Notebook isn't installed (but should be installed automatically when invoked without the `--skip-dependency-checks`...).

Try the following following from the IPyIDA console:

    !python3 -m pip install -y -U 'notebook<7'

This should install Jupyter Notebook, or display why it couldn't.

**Comment by lazydaemon** [comment]
It's already installed. When trying this command, I got the message that it's already installed. Importing in ``ipyida`` also works.
<img width="613" alt="Screenshot 2022-12-23 at 22 15 48" src="https://user-images.githubusercontent.com/3420941/209406232-84012cd9-80db-4c2a-be66-19d8d6e9416c.png">

Starting ``jupyter-notebook`` from the command line with the configured python version also works fine.

<img width="1213" alt="Screenshot 2022-12-23 at 22 16 57" src="https://user-images.githubusercontent.com/3420941/209406375-f1c16064-39fe-4bcc-a24d-32cf00e1ba4e.png">

**Comment by marc-etienne** [comment]
Hum looks like there is somehow two Python environments and stuff is getting installed at one place while being run from another place. It's also possible there's a `jupyter.py` somewhere that gets picked up before the "good" one. Check `sys.path` and look for a `jupyter.py` or `jupyter/__main__.py` in each dir.

Consider setting up a virtualenv for IDA, that would isolate these kind of problems, see [`README.virtualenv.adoc`](https://github.com/eset/ipyida/blob/master/README.virtualenv.adoc)

**Comment by lazydaemon** [comment]
I tested around a little bit and it seems, everything is working fine with my installed version of Python 3.10

``./idapyswitch --force-path /opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Python``

Off topic:
I tried to configure IDA with a Virtual Environment but it seems not to be that easy.
``Cannot determine python library version for "/Users/redacted/Documents/VirtualEnvs/ida_pro/bin/python": failed to determine libpython version: LC_ID_DYLIB not found``. Hex Rays Support told me to use the path to the `python*.dylib` which is of course correct. However, there is no `python*.dylib` in a Virtual Environment so how do you set up IDA with a python venv?

**Comment by marc-etienne** [comment]
It seems you are trying to switch to a virtualenv using `idapyswitch` perhaps? virtualenv should be activated from `~/.idapro/idapythonrc.py` using the [provided snippet](https://github.com/eset/ipyida/blob/master/README.virtualenv.adoc). In your case, replacing the last line with `activate_virtualenv("/Users/redacted/Documents/VirtualEnvs/ida_pro")`.

Ideally, make sur the virtualenv was created using the same Python version. `/Users/redacted/Documents/VirtualEnvs/ida_pro/bin/python` should be a symlink to `/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python`.

**Comment by lazydaemon** [comment]
> It seems you are trying to switch to a virtualenv using `idapyswitch` perhaps? virtualenv should be activated from `~/.idapro/idapythonrc.py` using the [provided snippet](https://github.com/eset/ipyida/blob/master/README.virtualenv.adoc). In your case, replacing the last line with `activate_virtualenv("/Users/redacted/Documents/VirtualEnvs/ida_pro")`.
> 
> Ideally, make sur the virtualenv was created using the same Python version. `/Users/redacted/Documents/VirtualEnvs/ida_pro/bin/python` should be a symlink to `/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/Resources/Python.app/Contents/MacOS/Python`.

Yeah, I've used idapyswitch to switch to the virtualenv. I just tested your snippet and it seems to work. However, my python setup is quite messed up right now so I will stick to my python installation mentioned above. Next time I install my OS, I will try to keep it clean from the beginning ;-). I guess we can close that issue.
